CONNECTION_TAB_DEFAULT_TITLE = "Untitled"
CONNECTION_STRING_SUPPORTED_DB_NAMES = ["SQLite", "MySQL"]
CONNECTION_STRING_PLACEHOLDER = "Enter..."

CONNECTION_STRING_SQL_LITE_DEFAULT = "demo.db"
CONNECTION_STRING_MYSQL_DEFAULT = "username=root;host=localhost;port=3306;dbname=mysql"

QUERY_EDITOR_DEFAULT_TEXT_SQL_LITE = "SELECT name FROM sqlite_master WHERE type='table'"
QUERY_EDITOR_DEFAULT_TEXT_MYSQL = "SHOW TABLES"

QUERY_CONTROL_CONNECT_BUTTON_TEXT = "Connect"
QUERY_CONTROL_EXECUTE_BUTTON_TEXT = "Execute"
QUERY_CONTROL_FETCH_BUTTON_TEXT = "Fetch"
QUERY_CONTROL_COMMIT_BUTTON_TEXT = "Commit"
QUERY_CONTROL_ROLLBACK_BUTTON_TEXT = "Rollback"
QUERY_RESULTS_DATA_TAB_TEXT = "Data"
QUERY_RESULTS_EVENTS_TAB_TEXT = "Events"
